# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    # Frontend must be pre-built by CI before goreleaser runs.
    # This hook verifies the build artifacts exist.
    - test -d frontend/build

builds:
  - id: kefw2ui
    main: .
    binary: kefw2ui
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
      - kefw2ui.service

homebrew_casks:
  - name: kefw2ui
    commit_author:
      name: Jens Hilligsoe
      email: github@hilli.dk
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/hilli/kefw2ui"
    description: "Web UI for controlling KEF W2 speakers"
    url:
      template: "https://github.com/hilli/kefw2ui/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/hilli/kefw2ui/"
    skip_upload: false
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kefw2ui"]
          end
    repository:
      owner: hilli
      name: homebrew-tap
      branch: release-kefw2ui-{{.Tag}}
      pull_request:
        enabled: true
        draft: false

changelog:
  disable: true

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/hilli/kefw2ui
    description: |-
      Web UI for controlling KEF W2 speakers (LSX Wireless II (LT)/LS50 Wireless II/LS60 Wireless)
    maintainer: Jens Hilligsøe <kefw2@hilli.dk>
    license: MIT
    vendor: Jens Hilligsøe
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/kefw2/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

dockers_v2:
  - images:
      - "ghcr.io/hilli/kefw2ui"
    id: kefw2ui
    dockerfile: Dockerfile.goreleaser
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "v{{.Version}}"
      - latest
      - "v{{.Major}}.{{.Minor}}"
    sbom: true
    labels:
      "org.opencontainers.image.description": "Web UI for controlling KEF W2 speakers"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

snapshot:
  version_template: "{{ incpatch .Version }}"